# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-windows.yaml

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        go: ["1.21"]
    name: Go ${{ matrix.go }} - windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Download SenzingApi
        run: curl --output c:\tmp\senzingapi.zip https://public-read-access.s3.amazonaws.com/staging/SenzingAPI_3.7.0.zip
      - run: pwd
      - name: Extract SenzingApi
        run: 7z x c:\tmp\senzing.zip -o c:\
      - run: dir c:\ /s
      - name: Run go test
        run: go test -v -p 1 ./...
